name: Pull data and subset

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'NOTES.txt'
      - 'README.md'
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests datetime
    - name: Decrypt tokens
      run: sh endur/decrypt_secret.sh
      env:
        STRAVA_TOKENS_PHRASE: ${{ secrets.STRAVA_TOKENS_PHRASE }}
    - name: Commit any changes to data files, including encrypted tokens
      run: |
        git config --local user.name "harveybarnhard"
        git add ./data
        git commit -m "Auto-updating Strava data and tokens"
    - name: Push encrypted tokens back to repository
      uses: ad-m/github-push-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
    # - name: Pull data
    #   run: |
    #     python endur/get_data_again.py
    # - name: Prepare data for visualization
    #   run: |
    #     python endur/data_sample.py
    # - name: Encrypt tokens
    #   run: |
    #     sh endur/encrypt_secret.sh
    #   env:
    #     STRAVA_TOKENS_PHRASE: ${{ secrets.STRAVA_TOKENS_PHRASE }}
    # - name: Commit any changes to data files, including encrypted tokens
    #   run: |
    #     git config --local user.name "harveybarnhard"
    #     git add ./data
    #     git commit -m "Auto-updating Strava data and tokens"
    # - name: Push encrypted tokens back to repository
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     force: true
