name: Pull data, visualize, and upload

on:
  push:
    branches: main
    paths-ignore:
      - 'LICENSE'
      - 'NOTES.txt'
      - 'README.md'
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests datetime
    - name: Pull data
      run: |
        python endur/get_data_again.py
    - name: Prepare data for visualization
      run: |
        python endur/data_sample.py
